name = "observo-dev"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { NODE_ENV = "development" }

[env.production]
vars = { NODE_ENV = "production" }

# 本地开发时的环境变量
[env.development.vars]
PROXY_TARGET_URL = "https://api.example.com"
PROXY_API_KEY = "your-api-key-here"

# 生产环境的环境变量
[env.production.vars]
PROXY_TARGET_URL = "https://api.production.com"
PROXY_API_KEY = "your-production-api-key"

# 本地开发配置
[dev]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
port = 8787
local_protocol = "http"
upstream_protocol = "https"

# 路由配置
[[routes]]
pattern = "localhost:3000/api/proxy/*"
zone_name = "localhost"

# KV 存储配置（如果需要）
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"